IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'REGISTRO_CURSOS')
BEGIN
	CREATE DATABASE REGISTRO_CURSOS;
END;
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'ALUMNO')
BEGIN
	CREATE TABLE ALUMNO(
	ALUMNO_ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CODIGO INT UNIQUE NOT NULL,
	CORREO VARCHAR(50) NOT NULL
	);
END;
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'CURSOS')
BEGIN
	CREATE TABLE CURSOS(
	CURSO_ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
	);
END;
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'MATRICULAS')
BEGIN
	CREATE TABLE MATRICULAS(
	CURSO_ID INT,
	CODIGO INT,

	PRIMARY KEY(CURSO_ID,CODIGO),
	CONSTRAINT FK_MATRICULAS_ALUMNO FOREIGN KEY (CODIGO) REFERENCES ALUMNO(CODIGO),
	CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(CURSO_ID)
	);
END;
GO

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE NAME = 'NOTAS')
BEGIN
	CREATE TABLE NOTAS(
	NOTA_ID INT IDENTITY(1,1) PRIMARY KEY,
	CURSO_ID INT,
	CODIGO INT,
	NOTA1 DECIMAL(4,2) NOT NULL,
	NOTA2 DECIMAL(4,2) NOT NULL,
	PROMEDIO DECIMAL(4,2),

	CONSTRAINT FK_NOTAS_MATRICULAS FOREIGN KEY (CURSO_ID,CODIGO) REFERENCES MATRICULAS(CURSO_ID,CODIGO)
	);
END;
GO


--INSERT INTO CURSOS(NOMBRE)
--VALUES
--('MATEMATICA'),('LENGUAJE'),('PSICOLOGIA');
--GO


USE REGISTRO_CURSOS;
GO
SELECT * FROM ALUMNO;
SELECT * FROM CURSOS;
SELECT * FROM MATRICULAS;
SELECT * FROM NOTAS;




USE MASTER;
GO
ALTER DATABASE REGISTRO_CURSOS SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE REGISTRO_CURSOS;
GO